config/routes.rb
Rails.application.routes.draw do
  resources :historico_convercas
  scope '/administrador' do
    resources :parcelas
    resources :valors
    resources :forma_pagamentos
    resources :produtos
    resources :enderecos
    resources :contatos
    resources :clientes
    resources :segmentos
    resources :vendas
  end

  devise_for :users, path: 'autenticar', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secreto', confirmation: 'verificacao', unlock: 'desbloquear', registration: 'registrar', sign_up: 'cadastrar' }

  get 'welcome/index'               => 'welcome#index'
  get '/'                           => 'welcome#index'
  post '/search'                    => 'welcome#search'
  
  
  get 'cliente-publicar/:id'        => 'clientes#cliente_publicar'
  get 'cliente-despublicar/:id'     => 'clientes#cliente_despublicar'
  get 'clientes'                    => 'clientes#index'
  
  get '/add_segmento_remote'        => 'segmentos#add_segmento_remoto'
  
  get 'admin'                       => 'administrador#index'
  get 'administrador'               => 'administrador#index'
  get 'admin/segmentos'             => 'administrador#segmento'
  get 'admin/vendas'                => 'administrador#venda'
  
  post '/venda-search'              => 'vendas#search'
  get '/venda/show/:id'             => 'vendas#show'
  get '/vendas/:id/cliente'         => 'vendas#new'
  
  get '/reloadParcelas'             =>'vendas#gera_parcelas'
  get '/reloadTotal'                =>'vendas#get_valor'

  get '/loadHistorico'              => 'historico_convercas#reload'

  put '/baixar-parcela/:id'          =>'parcelas#baixar_parcela'
  put '/reabrir-parcela/:id'         =>'parcelas#reabrir_parcela'
  
  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :cliente_segmentos, dependent: :destroy
	has_many :contatos, dependent: :destroy
	has_many :enderecos, dependent: :destroy
	

	has_many :segmentos, through: :cliente_segmentos
	
	has_many :vendas
	
	validates :responsavel,:razao_social, :contatos, presence: true
	validates :razao_social ,uniqueness: true	

	accepts_nested_attributes_for :contatos, allow_destroy: true
	accepts_nested_attributes_for :enderecos, allow_destroy: true

	paginates_per 10

	mount_uploader :banner, BannerUploader

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy, :cliente_publicar, :cliente_despublicar]
  before_action :get_all_segmentos, only: [:index, :new, :show,:edit, :destroy]
  before_action :get_all, only: [:index, :destroy, :update,:cliente_publicar, :cliente_despublicar]
  skip_before_action :verify_authenticity_token
  layout 'admin'

  before_action :authenticate_user!

  # GET /clientes
  # GET /clientes.json
  def index
    
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @action = 'show'
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    @cliente.contatos.build
    @cliente.enderecos.build
    
  end

  # GET /clientes/1/edit
  def edit
    @action = 'update'
    respond_to do |format|
      format.js { render :new, location: @action}
    end
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params) 
    
    respond_to do |format|
      if @cliente.save
        @action = 'success'        
        @cliente_segmento = @cliente.cliente_segmentos.new 
        format.html { redirect_to clientes_path, notice: 'Cliente criado com sucesso!' }
        #redirect_to({action: 'index'}, notice: 'Cliente criado com sucesso!')
      else
        @text = "Opss! ocorreu um erro!"
        @action = 'danger'
        format.js { render :new }
       
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
         format.html { redirect_to clientes_path, notice: 'Cliente atualizado com sucesso.' }
        
      else
        
        format.html { render :edit }
        
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    if @cliente.destroy
      respond_to do |format|
        @action = 'success'
        @text = 'Cliente excluido com sucesso!'
        format.js { redirect_to clientes_path, notice: 'Cliente Deletado.' }      
      end  
    else
      @text = 'Opss! ocorreu um erro' 
      @action = 'danger'
    end
  end

  def cliente_publicar
    @cliente.update_attributes(publicar: true)
    respond_to do |format|        
      format.js { render :index}
    end

  end  
  def cliente_despublicar
    @cliente.update_attributes(publicar: false)
    respond_to do |format|
      format.js { render :index}
    end
  end  

  private
      
    def get_all
      @clientes_count = Cliente.count
      @clientes = Cliente.order(:razao_social).page params[:page]
    end

    def get_all_segmentos
      @segmentos = Segmento.all
    end  

    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:responsavel, :razao_social, :banner, :segmento_ids=>[], :contatos_attributes => [:id, :numero, :_destroy, :whatsapp], :enderecos_attributes => [:id, :end, :numero, :complemento])
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_clientes_all.html.erb
<% @clientes.each do |cliente| %>      
      <tr>
        <td colspan="2"><%= cliente.razao_social %></td>
        <td>
          
              <%= link_to 'Segmento', "#collapseSegmentos_#{cliente.id}", role: :button,
                    data: { parent: '#accordion', toggle: :collapse},
                    aria: { controls: :collapseOne, expanded: false }, class: 'btn btn-default'  %>
            
              <div class="collapse" id=<%="collapseSegmentos_#{cliente.id}"%>>
                <% cliente.segmentos.each do |cs| %>                  
                    <%= cs.descricao %>
                    <br />
                <% end %>
              </div>
        </td>
        <td><%= cliente.publicar ? 'publicado': ''  %></td>
        <td>
             
              <%= link_to 'Vender', "/vendas/#{cliente.id}/cliente", class: 'btn btn-success btn-xs', remote: true %>
              
              <%= link_to 'Detalhes', cliente, class: 'btn btn-default  btn-xs', remote: true %>
              <%= link_to 'Editar', edit_cliente_path(cliente), class: 'btn btn-default  btn-xs', remote: true %>
              <%= link_to 'Apagar', cliente, method: :delete, remote: true, data: { confirm: 'Deseja proseguir?' }, class: 'btn btn-danger  btn-xs' %>
          
        </td>
      </tr>
    <% end %>

app/views/clientes/_contato_fields.html.erb
<div class="panel-body">
	<div class="form-group nested-fields">
		
	  <div class="input-bar">
			<div class="input-bar-item">
	    		<%= f.input :whatsapp, as: :boolean, boolean_style: :inline %>
	    	</div>
	    	<div class="input-bar-item">
	    		<%= f.text_field :numero, class: 'form-control telefones', placeholder: 'Digite o Telefone aqui...'  %>
			</div>
	    	<div class="input-bar-item">
	    		<%= link_to_remove_association "remove", f, class: 'btn btn-danger btn-remove-contact' %>	
	    	</div>	
	    </div>	
	</div>
</div>


<script>
	$(function() {
  		$('.input-bar-item').on('keydown', '#cliente_enderecos_attributes_0_numero', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
})
</script>

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente, html: {remote: true, multipart: true}) do |f| %>
    <%= f.error_notification %>

  <div class="panel panel-default">
    <div class="panel-heading">Dados do cliente</div>
    <div class="panel-body">
          <div class="form-group form-inputs">
              <%= f.input :banner, as: :file %>
              
              <%= f.input :razao_social, class: 'form-control', placeholder: 'Digite aqui a razão social do cliente...', autofocus: true %>  
            
              <%= f.input :responsavel, class: 'form-control', placeholder: 'Digite aqui o Responsavel...'%>   
            
          </div>
    </div>    
  </div>
  
  <hr />
  <div id='contatos' class='panel panel-default'>
      <div class="panel-heading">Contato</div>
      
          <!-- Link Gem cocoon --> 
          <%= link_to_add_association '+', f , :contatos, 'data-association-insertion-node' => "#contatos", 'data-association-insertion-method' => 'append', class: 'btnAdd btn btn-primary btn-New-Contact' %>    
          <%= f.simple_fields_for :contatos do |contato| %>          
              <%= render 'contato_fields',  f: contato  %>
          <% end %>
      
  </div>

  <div  class='panel panel-default'>
      <div class="panel-heading">Endereço</div>
      <div class="panel-body">
        <%= f.simple_fields_for :enderecos do |e| %>          
              <%= render 'enderecos/form',  f: e  %>
          <% end %>
      </div>     
      
  </div>

  <div  class='panel panel-default'>
      <div class="panel-heading">Área de atuação</div>
      <div class="panel-body">
        <%= link_to "+", '/add_segmento_remote', { class: 'btnAdd btn btn-primary', 'data-toggle' => 'tooltip', :title => 'Novo Segmento',remote: true }%>       
        <div id="show_segmentos">
          <%= render 'segmentos/show_all_segmentos_checkbox', f: f %>          
        </div>
      </div>
  </div>  

  <div class="actions">
    <%= f.button :submit, "Gravar", class: 'btn btn-primary'  %>
    <%= link_to 'Cancelar', '/admin', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/clientes/_form_modal.html.erb
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= @action.eql?('update') ? "Atualizando Cliente" : "Novo Cliente"%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "clientes/form" %>        
      </div>      
    </div>
  </div>

app/views/clientes/_index.html.erb
<% if notice %>
    <%= javascript_tag "Materialize.toast('#{notice}', 8000)" %>
<% end %>  

<ol class="breadcrumb">
  <li><%= link_to 'Administrador', admin_path  %></li>
  <li>Clientes</li>    
</ol>

<%= link_to raw("<i class='glyphicon glyphicon-plus'></i>"), new_cliente_path, class: 'btnAdd btnNew btn btn-primary', remote: true%>

<%= paginate @clientes, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>
<table class='table table-striped'>
  <thead>
    <tr>
      <th  colspan="2">Cliente</th>
      <th>Segmentos</th>

      <th colspan="2"></th>
    </tr>
  </thead>
  
  <tbody id='clientes'>
    total de <%= @clientes_count%>
    <%= render partial: 'clientes/clientes_all' %>
  </tbody>
</table>
<div id="admin-modal" class="modal fade"></div>

app/views/clientes/_msn.html.erb
	
  <%= alert(@action, @text) %>

app/views/clientes/_show.html.erb
<p id="notice"><%= notice %></p>

<div class='pag-show'>
	<div class='banner'>			
		
		<% if @cliente.banner.blank? %>						
			<img src="http://via.placeholder.com/250x220" alt="" class='img-responsive'>
		<% else %>	
			<%= image_tag(@cliente.banner.url(:medium),:crop => :thumb, :gravity => :face) %>
		<% end %>			
	</div>
	<div class='dados'>
				
		

				<p>
		  <strong>Razão Social:</strong>
		  	
		  	<%= @cliente.razao_social %>
		  <br />
		  <strong>Responsável:</strong>
		  	<%= @cliente.responsavel %>	
		</p>
		<p>
			<strong>Endereço:</strong>
			<br />
			<% @cliente.enderecos.each do |e|%>
										
				<%= e.end unless e.end.blank? %>
				<% unless e.end.blank? %>
					<%= e.numero ? ' - s/n' :  "-  #{e.numero}" %>		
				<% end %>
				<%= ' - ' + e.complemento unless e.complemento.blank?  %>
											
			<% end %>
		</p>
			<p>
				<strong>Segmento</strong>
				<ul>
					<% @cliente.segmentos.each do |s|%>
						<li>
							<%= s.descricao %>					
						</li>
					<% end %>			
				</ul>
			</p>
		<p>
			<strong>Contatos: </strong>
			<br />
			<% @cliente.contatos.each do |c|%>
				<% if c.whatsapp == '1' %>
					<i class="fa fa-whatsapp" aria-hidden="true"></i>
				<% else %>								
					<i class="fa fa-phone" aria-hidden="true"></i>
				<% end %>	
				<%= c.numero %> <br />	
								
			<% end %>
		</p>
</div>	
</div>


<%= link_to 'Editar', edit_cliente_path(@cliente), remote: true,class: 'btn btn-default btn-show-editar' %>

app/views/clientes/_show_modal.html.erb
 <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cliente <%= @cliente.razao_social %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "show" %>
      </div>
      
    </div>
  </div>

app/views/clientes/edit.html.erb
<h1>Editando Clientes</h1>

<%= render 'form', cliente: @cliente %>
<div id="segmento-modal" class="modal fade"></div>

<%= link_to 'Voltar', '/admin', class: 'btn btn-default' %>

app/views/clientes/index.html.erb
<%= render 'clientes/index' %>

app/views/clientes/index.js.erb
<% if @location = 'adm' %>
$('#principal-adm').html('<%= escape_javascript (render "clientes/index") %>');
<% else %>
	$('#panel-msn').html('<%= escape_javascript (render partial: "msn") %>');
	$('#clientes').html('<%= escape_javascript (render partial: "index", location: @clientes) %>');
<% end %>

app/views/clientes/new.html.erb
<div class="jumbotron">
	<h4 class='text-center'>Cadastro de novo Cliente</h4>
</div>	
<%= link_to 'Voltar', clientes_path, class: 'btn btn-default btn-new-cliente-voltar' %>
<%= render 'form', cliente: @cliente %>
<!--<div id="segmento-modal" class="modal fade"></div>-->

app/views/clientes/new.js.erb
	$('#admin-modal').html('<%= escape_javascript (render partial: "form_modal" , location: @cliente) %>');
	$("#admin-modal").modal("show");

app/views/clientes/show.js.erb
$('#admin-modal').html('<%= escape_javascript (render partial: "show_modal", location: @cliente) %>');
$("#admin-modal").modal("show");