config/routes.rb
Rails.application.routes.draw do
  resources :historico_convercas
  scope '/administrador' do
    resources :parcelas
    resources :valors
    resources :forma_pagamentos
    resources :produtos
    resources :enderecos
    resources :contatos
    resources :clientes
    resources :segmentos
    resources :vendas
  end

  devise_for :users, path: 'autenticar', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secreto', confirmation: 'verificacao', unlock: 'desbloquear', registration: 'registrar', sign_up: 'cadastrar' }

  get 'welcome/index'               => 'welcome#index'
  get '/'                           => 'welcome#index'
  post '/search'                    => 'welcome#search'
  
  
  get 'cliente-publicar/:id'        => 'clientes#cliente_publicar'
  get 'cliente-despublicar/:id'     => 'clientes#cliente_despublicar'
  get 'clientes'                    => 'clientes#index'
  
  get '/add_segmento_remote'        => 'segmentos#add_segmento_remoto'
  
  get 'admin'                       => 'administrador#index'
  get 'administrador'               => 'administrador#index'
  get 'admin/segmentos'             => 'administrador#segmento'
  get 'admin/vendas'                => 'administrador#venda'
  
  post '/venda-search'              => 'vendas#search'
  get '/venda/show/:id'             => 'vendas#show'
  get '/vendas/:id/cliente'         => 'vendas#new'
  
  get '/reloadParcelas'             =>'vendas#gera_parcelas'
  get '/reloadTotal'                =>'vendas#get_valor'

  get '/loadHistorico'              => 'historico_convercas#reload'

  put '/baixar-parcela/:id'          =>'parcelas#baixar_parcela'
  put '/reabrir-parcela/:id'         =>'parcelas#reabrir_parcela'
  
  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :cliente_segmentos, dependent: :destroy
	has_many :contatos, dependent: :destroy
	has_many :enderecos, dependent: :destroy
	

	has_many :segmentos, through: :cliente_segmentos
	
	has_many :vendas
	
	validates :responsavel,:razao_social, :contatos, presence: true
	validates :razao_social ,uniqueness: true	

	accepts_nested_attributes_for :contatos, allow_destroy: true
	accepts_nested_attributes_for :enderecos, allow_destroy: true

	paginates_per 10

	mount_uploader :banner, BannerUploader

end

app/models/cliente_segmento.rb
class ClienteSegmento < ApplicationRecord
  belongs_to :cliente
  belongs_to :segmento
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :cliente, optional: true

  validates :numero, presence: true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cliente, optional: true

  
end

app/models/forma_pagamento.rb
class FormaPagamento < ApplicationRecord
	has_many :vendas

	validates :descricao, presence: true
end

app/models/parcela.rb
class Parcela < ApplicationRecord
  belongs_to :venda, optional: true

  
end

app/models/produto.rb
class Produto < ApplicationRecord
	
	has_many :venda_produtos, dependent: :destroy
	has_many :vendas, through: :venda_produtos	
	
	has_many :produto_valors, dependent: :destroy
	has_many :valors, through: :produto_valors

	accepts_nested_attributes_for :valors, allow_destroy: true, reject_if: :all_blank 
end

app/models/produto_valor.rb
class ProdutoValor < ApplicationRecord
  belongs_to :produto
  belongs_to :valor
end

app/models/segmento.rb
class Segmento < ApplicationRecord
	has_many :cliente_segmentos, dependent: :destroy
	
	has_many :clientes, through: :cliente_segmentos	

	validates :descricao, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :vendas
  has_many :historico_convercas
end

app/models/valor.rb
class Valor < ApplicationRecord
	has_many :produto_valors, dependent: :destroy
	has_many :produtos, through: :produto_valors
end

app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :user
  belongs_to :cliente  
  belongs_to :forma_pagamento

  has_many :venda_produtos, dependent: :destroy
  has_many :produtos, through: :venda_produtos
  
  has_many :parcelas, dependent: :destroy
  accepts_nested_attributes_for :parcelas, allow_destroy: true, reject_if: :all_blank  
  
  has_many :historico_convercas, dependent: :destroy
  accepts_nested_attributes_for :historico_convercas, allow_destroy: true, reject_if: :all_blank  
  
  validates :valor_total, presence: true


  paginates_per 10
end

app/models/venda_produto.rb
class VendaProduto < ApplicationRecord
  belongs_to :venda
  belongs_to :produto
end

app/controllers/administrador_controller.rb
class AdministradorController < ApplicationController

	layout 'admin'

	before_action :authenticate_user!

	def index				
		#graficos
		@valor_vendas 		= Venda.group('extract( month from created_at)').sum('valor_total')
		@vendas 	  		= Venda.group('extract( month from created_at)').count

		query = Parcela.where('vencimento < ? AND status = ?', Time.new.yesterday, false)
		@parcelas_atrasadas = query.page params[:page]
		@parcelas_atrasadas_count = @parcelas_atrasadas.count
	end

	def segmento		
		@segmentos = Segmento.all		
		render 'segmentos/index'
		
	end

	def venda		
		@vendas = Venda.all
		#@location = 'adm'
		render 'vendas/index'
		
	end
end

app/helpers/administrador_helper.rb
module AdministradorHelper

	require "#{Rails.root}/lib/mes.rb"

	def converte_mes(m)
		mes = Mes.new(m).get_mes_extensio.to_s
	end

end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/parcelas_helper.rb
module ParcelasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/valors_helper.rb
module ValorsHelper
end

app/helpers/vendas_helper.rb
module VendasHelper

	require "#{Rails.root}/lib/desconto.rb"

	def desconto(des,val)
		des = Desconto.new(des,val).valor_com_desconto.to_f
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def listar_Cliente(s)
		 raw('<h3>'+s.nome+'</h3>')
								
		raw('<h6><strong>Segmento</strong></h6>')
		s.segmentos.each do |s|
			raw'<i class="glyphicon glyphicon-ok"></i>'+s.descricao+ '<br />'
		end
		raw('<hr />')				
		raw('<h6><strong>Contato</strong></h6>')
		s.contatos.each do |c|
			if c.whatsapp
				raw('<i class="fa fa-whatsapp fa-5x" aria-hidden="true"></i>')
				c.numero 
				raw('<br />')
			end
			if c.whatsapp != true
				raw('<i class="fa fa-phone" aria-hidden="true"></i>')
				c.numero 
				raw('<br />')
			end
									
		end
		raw('<hr />')
		raw('<h6><strong>Endereço</strong></h6>')				
		s.enderecos.each do |e|								
			e.end 
			raw('-') 
			e.numero 
			unless e.complemento.blank?
				e.complemento
				raw('-')
			end							
		end

	end

end

app/views/administrador/_grafico_valor_em_vendas.js.erb
<script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        
        var data = google.visualization.arrayToDataTable([
          ['Mês', 'Vendas'],
          <% @valor_vendas.each do |k,v| %>
            [ '<%= converte_mes(k) %>', <%= v %>],
          <% end %>
        ]);


        var options = {
          chart: {
            title: 'Valor em vendas(R$:)'
            
          },
          bars: 'vertical',
          vAxis: {format: 'decimal'},
          height: 300,
          width: 400,
          legend: { position: 'none' },
          colors: ['#d95f02']
        };

        var chart = new google.charts.Bar(document.getElementById('columnchart_material_valor_vendas'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
  
  // pequisa e agrupa por mes e soma valor das vendas
  //Venda.where("extract( month from created_at) = ?", Time.new.month).group('extract( month from created_at)').sum('valor_total')
      }
    </script>

  
  

app/views/administrador/_grafico_vendas.js.erb
<script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        
        var data = google.visualization.arrayToDataTable([
          ['Mês', 'Vendas'],
          <% @vendas.each do |k,v| %>
            [ '<%= converte_mes(k) %>', <%= v %>],
          <% end %>
        ]);


        var options = {
          chart: {
            title: 'Vendas'
            
          },
          bars: 'vertical',
          vAxis: {format: 'decimal'},
          height: 300,
          width: 400,
          legend: { position: 'none' },
          colors: ['#8A8ABE']
        };

        var chart = new google.charts.Bar(document.getElementById('columnchart_material_vendas'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
  
  // pequisa e agrupa por mes e soma valor das vendas
  //Venda.where("extract( month from created_at) = ?", Time.new.month).group('extract( month from created_at)').sum('valor_total')
      }
    </script>

  

app/views/administrador/_menu.html.erb
<div class="sidebar">
  <nav id="menu">
    <ul class='nav nav-pills nav-stacked'>      
      <li> <%= link_to "Add Cliente", clientes_path, class: 'btn waves-light'  %></li>
      <li> <%= link_to "Add Venda", clientes_path, class: 'btn waves-light'  %></li>
      <li> <%= link_to "Segmentos", segmentos_path, class: 'btn waves-light' %></li>      
      <li> <%= link_to 'Produtos', produtos_path, class: 'btn waves-light' %></li>  
      <li> <%= link_to 'Forma Pag', forma_pagamentos_path, class: 'btn waves-light' %></li>  
      <li> <%= link_to 'Rel.Vendas', vendas_path, class: 'btn waves-red waves-effect' %></li>  
      <li> <%= link_to 'Relatório', administrador_path, class: 'btn waves-light' %></li>  
    </ul>
  </nav>
</div>

app/views/administrador/_parcelas_atrasadas.html.erb
<% if @parcelas_atrasadas %>
	
	<%= paginate @parcelas_atrasadas, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>
	
	<table class="table table-striped">
		<thead>
			<th>Cliente</th>			
			<th>Vencimento</th>
			<th>Valor</th>
			<th></th>
		</thead>
		<tbody>
			<% @parcelas_atrasadas.each do |p| %>	
				<tr>
					<td><%= p.venda.cliente.razao_social %></td>
					<td><%= I18n.l(p.vencimento) %></td>
					<td><%= p.valor %></td>
					<td>
						<%= link_to 'Cliente', cliente_path(p.venda.cliente_id), remote: true,class: 'btn red lighten-1' %>
					</td>
				</tr>
			<% end %>	
		</tbody>
	</table>
<% end %>	

app/views/administrador/index.html.erb
<% if notice %>
  <%= javascript_tag "Materialize.toast('#{notice}', 8000)" %>
<% end %>
<head>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>    
      <% if @parcelas_atrasadas_count > 0 %>
        <fieldset>
        	<legend>Parcelas Vencidas</legend>
        	   <div class="alert alert-danger">
                Existem <%= @parcelas_atrasadas_count %> parcelas em aberto
                <%= link_to 'Detalhes', "#collapseParcelasAdm", role: :button,
                      data: { parent: '#accordion', toggle: :collapse},
                      aria: { controls: :collapseOne, expanded: false }, class: 'alert-link'  %>
              </div>

               <div class="collapse" id="collapseParcelasAdm">
                <%= render 'parcelas_atrasadas' %>		
              </div>
        </fieldset>
	   <% end %>
		<fieldset>
			<legend>Visão Total</legend>
		    <%= render 'grafico_valor_em_vendas.js' %>
		    <%= render 'grafico_vendas.js' %>
		</fieldset>

  </head>
  <body>
  <div class="painel-graficos">
    <span id="columnchart_material_valor_vendas" style="width: 400px; height: 200px;"></span>
    <span id="columnchart_material_vendas" style="width: 600px; height: 300px;"></span>  	
  </div>
  </body>
