config/routes.rb
Rails.application.routes.draw do
  resources :historico_convercas
  scope '/administrador' do
    resources :parcelas
    resources :valors
    resources :forma_pagamentos
    resources :produtos
    resources :enderecos
    resources :contatos
    resources :clientes
    resources :segmentos
    resources :vendas
  end

  devise_for :users, path: 'autenticar', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secreto', confirmation: 'verificacao', unlock: 'desbloquear', registration: 'registrar', sign_up: 'cadastrar' }

  get 'welcome/index'               => 'welcome#index'
  get '/'                           => 'welcome#index'
  post '/search'                    => 'welcome#search'
  
  
  get 'cliente-publicar/:id'        => 'clientes#cliente_publicar'
  get 'cliente-despublicar/:id'     => 'clientes#cliente_despublicar'
  get 'clientes'                    => 'clientes#index'
  
  get '/add_segmento_remote'        => 'segmentos#add_segmento_remoto'
  
  get 'admin'                       => 'administrador#index'
  get 'administrador'               => 'administrador#index'
  get 'admin/segmentos'             => 'administrador#segmento'
  get 'admin/vendas'                => 'administrador#venda'
  
  post '/venda-search'              => 'vendas#search'
  get '/venda/show/:id'             => 'vendas#show'
  get '/vendas/:id/cliente'         => 'vendas#new'
  
  get '/reloadParcelas'             =>'vendas#gera_parcelas'
  get '/reloadTotal'                =>'vendas#get_valor'

  get '/loadHistorico'              => 'historico_convercas#reload'

  put '/baixar-parcela/:id'          =>'parcelas#baixar_parcela'
  put '/reabrir-parcela/:id'         =>'parcelas#reabrir_parcela'
  
  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :cliente_segmentos, dependent: :destroy
	has_many :contatos, dependent: :destroy
	has_many :enderecos, dependent: :destroy
	

	has_many :segmentos, through: :cliente_segmentos
	
	has_many :vendas
	
	validates :responsavel,:razao_social, :contatos, presence: true
	validates :razao_social ,uniqueness: true	

	accepts_nested_attributes_for :contatos, allow_destroy: true
	accepts_nested_attributes_for :enderecos, allow_destroy: true

	paginates_per 10

	mount_uploader :banner, BannerUploader

end

app/models/cliente_segmento.rb
class ClienteSegmento < ApplicationRecord
  belongs_to :cliente
  belongs_to :segmento
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :cliente, optional: true

  validates :numero, presence: true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cliente, optional: true

  
end

app/models/forma_pagamento.rb
class FormaPagamento < ApplicationRecord
	has_many :vendas

	validates :descricao, presence: true
end

app/models/parcela.rb
class Parcela < ApplicationRecord
  belongs_to :venda, optional: true

  
end

app/models/produto.rb
class Produto < ApplicationRecord
	
	has_many :venda_produtos, dependent: :destroy
	has_many :vendas, through: :venda_produtos	
	
	has_many :produto_valors, dependent: :destroy
	has_many :valors, through: :produto_valors

	accepts_nested_attributes_for :valors, allow_destroy: true, reject_if: :all_blank 
end

app/models/produto_valor.rb
class ProdutoValor < ApplicationRecord
  belongs_to :produto
  belongs_to :valor
end

app/models/segmento.rb
class Segmento < ApplicationRecord
	has_many :cliente_segmentos, dependent: :destroy
	
	has_many :clientes, through: :cliente_segmentos	

	validates :descricao, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :vendas
  has_many :historico_convercas
end

app/models/valor.rb
class Valor < ApplicationRecord
	has_many :produto_valors, dependent: :destroy
	has_many :produtos, through: :produto_valors
end

app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :user
  belongs_to :cliente  
  belongs_to :forma_pagamento

  has_many :venda_produtos, dependent: :destroy
  has_many :produtos, through: :venda_produtos
  
  has_many :parcelas, dependent: :destroy
  accepts_nested_attributes_for :parcelas, allow_destroy: true, reject_if: :all_blank  
  
  has_many :historico_convercas, dependent: :destroy
  accepts_nested_attributes_for :historico_convercas, allow_destroy: true, reject_if: :all_blank  
  
  validates :valor_total, presence: true


  paginates_per 10
end

app/models/venda_produto.rb
class VendaProduto < ApplicationRecord
  belongs_to :venda
  belongs_to :produto
end

app/controllers/segmentos_controller.rb
class SegmentosController < ApplicationController
  before_action :set_segmento, only: [:show, :edit, :update, :destroy]
  before_action :get_all_segmentos, only: [:index, :create, :update, :destroy]  

  layout 'admin'

  before_action :authenticate_user!
  
  # GET /segmentos
  # GET /segmentos.json
  def index
    
  end

  # GET /segmentos/1
  # GET /segmentos/1.json
  def show
  end

  # GET /segmentos/new
  def new
    @segmento = Segmento.new

  end

  # GET /segmentos/1/edit
  def edit
    @action = 'update'
    respond_to do |format|
      format.js { render :new}
    end
  end

  # POST /segmentos
  # POST /segmentos.json
  def create
    @segmento = Segmento.new(segmento_params)
    
    respond_to do |format|
      if @segmento.save
        @cliente = Cliente.new        
        #if @action
          format.html {redirect_to segmentos_path, location: @cliente, notice: 'Segmento criado com sucesso!' }
        #else
        #  format.js { render :index, notice: 'Opss! ocorreu um erro.' }
        #end
      else
        format.js { render :new }
        
      end
    end
  end

  # PATCH/PUT /segmentos/1
  # PATCH/PUT /segmentos/1.json
  def update
    respond_to do |format|
      if @segmento.update(segmento_params) 
        @status = 'green'       
        format.js { redirect_to segmentos_path, notice: 'Segmento atualizado com secesso!' }        
      else
        @status = 'red'       
        format.js { render :new, notice: 'Opss! ocorreu um erro.' }
        
      end
    end
  end

  # DELETE /segmentos/1
  # DELETE /segmentos/1.json
  def destroy
    @segmento.destroy
    respond_to do |format|
      format.js { redirect_to segmentos_path, notice: 'Segmento deletado.' }
      
    end
  end


  def add_segmento_remoto
   @segmento = Segmento.new
   @action = true
    respond_to do |format|
      format.js { render :new}
    end
  end

  private
    def get_all_segmentos
      @segmento_count = Segmento.count
      @segmentos = Segmento.page(params[:page]).per(15)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_segmento
      @segmento = Segmento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segmento_params
      params.require(:segmento).permit(:descricao)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/parcelas_helper.rb
module ParcelasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/segmentos_helper.rb
module SegmentosHelper
end

app/helpers/valors_helper.rb
module ValorsHelper
end

app/helpers/vendas_helper.rb
module VendasHelper

	require "#{Rails.root}/lib/desconto.rb"

	def desconto(des,val)
		des = Desconto.new(des,val).valor_com_desconto.to_f
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def listar_Cliente(s)
		 raw('<h3>'+s.nome+'</h3>')
								
		raw('<h6><strong>Segmento</strong></h6>')
		s.segmentos.each do |s|
			raw'<i class="glyphicon glyphicon-ok"></i>'+s.descricao+ '<br />'
		end
		raw('<hr />')				
		raw('<h6><strong>Contato</strong></h6>')
		s.contatos.each do |c|
			if c.whatsapp
				raw('<i class="fa fa-whatsapp fa-5x" aria-hidden="true"></i>')
				c.numero 
				raw('<br />')
			end
			if c.whatsapp != true
				raw('<i class="fa fa-phone" aria-hidden="true"></i>')
				c.numero 
				raw('<br />')
			end
									
		end
		raw('<hr />')
		raw('<h6><strong>Endereço</strong></h6>')				
		s.enderecos.each do |e|								
			e.end 
			raw('-') 
			e.numero 
			unless e.complemento.blank?
				e.complemento
				raw('-')
			end							
		end

	end

end

app/views/segmentos/_form.html.erb
<%= simple_form_for(@segmento, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">    
    <%= f.input :descricao, class: 'form-control', autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Incluir" %>
  </div>
<% end %>

app/views/segmentos/_form_modal.html.erb
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= @action.eql?('update') ? "Atualizando Segmento" : "Novo Segmento"%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "form" %>        
      </div>
      
    </div>
  </div>

app/views/segmentos/_index.html.erb
<% if notice %>  
    <%= javascript_tag "Materialize.toast('#{notice}', 8000)" %>  
<% end %>  

<ol class="breadcrumb">
  <li><%= link_to 'Administrador', admin_path  %></li>
  <li>Segmentos</li>    
</ol>

<%= link_to raw("<i class='glyphicon glyphicon-plus'></i>"), new_segmento_path, class: 'btn btn-primary btnAdd btnNew', remote: true %>
<p>
  <hr />
  total de <%= @segmento_count %>  
  <hr />
</p>
    


<%= paginate @segmentos, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segmentos.each do |segmento| %>
      <tr>
        <td><%= segmento.descricao %></td>        
        <td>
          <%= link_to 'Editar', edit_segmento_path(segmento), class: 'btn btn-default', remote: true %>
          <%= link_to 'Apagar', segmento, method: :delete, data: { confirm: 'Deseja proceguir?' }, class: 'btn btn-danger', remote: true %>
            
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @segmentos, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>
<br>

app/views/segmentos/_show_all_segmentos_checkbox.html.erb
<div class="show_segmentos">
	<% unless @action.eql?('update') %>
	      <% for segmento in Segmento.all %>
		    <span>
		    	<%= label_tag "cliente_segmento_ids_#{segmento.id}" do %>
				    <%= check_box_tag "cliente[segmento_ids][]", segmento.id %>
				    <%= label_tag "cliente_segmento_ids_#{segmento.id}",segmento.descricao, class: 'collection_check_boxes' %>
		    	<% end %>
		    </span>
		  <% end %>
	<% else %>  		
	      <%= f.collection_check_boxes(:segmento_ids, Segmento.all, :id, :descricao) %> 
	<% end %>	
</div>

	


app/views/segmentos/create.js.erb
$('#show_segmentos').html('<%= escape_javascript (render "show_all_segmentos_checkbox", f: @cliente) %>');
$("#segmento-modal").modal("hide");

app/views/segmentos/create_2.js.erb
$('#show_segmentos').html('<%= escape_javascript (render "show_all_segmentos_checkbox", f: @cliente) %>');
$("#segmento-modal").modal("hide");

app/views/segmentos/edit.html.erb
<h1>Editado Segmento</h1>

<%= render 'form', segmento: @segmento %>


<%= link_to 'Voltar', segmentos_path, class: 'btn btn-default' %>

app/views/segmentos/index.html.erb
<%= render 'segmentos/index' %>

app/views/segmentos/index.js.erb
$('#admin-modal').modal("hide");
$('#principal-adm').html('<%= escape_javascript (render "segmentos/index") %>');

app/views/segmentos/new.html.erb
<h1>New Segmento</h1>

<%= render 'form', segmento: @segmento %>

<%= link_to 'Back', segmentos_path %>

app/views/segmentos/new.js.erb
	$('#admin-modal').html('<%= escape_javascript (render partial: "form_modal" , location: @segmento) %>');
	$("#admin-modal").modal("show");


	

app/views/segmentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @segmento.descricao %>
</p>

<%= link_to 'Edit', edit_segmento_path(@segmento) %> |
<%= link_to 'Back', segmentos_path %>